config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
      }
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  get 'users/detail'
  root 'posts#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
      redirect_back(fallback_location: root_path)
  end
    
  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if current_user.already_liked?(@post) %>
  <%= link_to image_tag("icon_red_heart.png"), post_like_path(@post), method: :delete, remote: true %>
<% else %>
  <%= link_to image_tag("icon_heart.png"), post_likes_path(@post), method: :post, remote: true %>
<% end %>

<h5>いいね件数: <%= @post.likes.count %></h5>

<h5>いいねしたユーザー</h5>
  <% @post.liked_users.each do |user| %>
    <h6><%= user.username %></h6>
  <% end %>