config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
      }
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  get 'users/detail'
  root 'posts#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark">
  <div class="container">
    <span class="text-white">SubScription Picker</span>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="/">サブスク・マニア</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <p class="navbar-text text-white">
          ログイン中のユーザー：<%= "#{current_user.username}" %>
        </p>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "btn btn-light text-black" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'プロフィール詳細', users_detail_path, class: "btn btn-success text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to 'プロフィール変更', edit_user_registration_path, class: "btn btn-warning text-white" %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, class: "btn btn-danger text-white", method: :delete %> 
        </li>
        <li class="nav-item">
          <%= link_to '新規投稿', new_post_path, class: "btn btn-primary text-white" %>
        </li>
      <% else %>
        <li>
          <%= link_to "新規登録", new_user_registration_path, class: "btn btn-primary text-white" %></li>
        <li>
        <li>
          <%= link_to "サインイン", new_user_session_path, class: "btn btn-success text-white" %>
        </li>
    <% end %>
    </ul>
    </div>
</nav>